version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: VyxjuI9zLQVx5pa15banWW6Wpf4QiBTxthEoxizNeYsDFOVX16sNiETpIPzvrqEd
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
